version: '2'
services:
  postgres:
    restart: always
    image: postgres:11.5
    volumes:
      - /var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=$PASSWORD
      - POSTGRES_USER=$USER
      - POSTGRES_DB=$DB_NAME

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
      - ./nginx_logs:/var/log/nginx/
    depends_on:
      - web

  web:
    image: icloud
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - ./wait-for-postgres.sh
      - ./entrypoint.sh
    volumes:
      - .:/src
      - ./static:/static
      - ./media:/media
      - ./nginx_logs:/nginx_logs
    expose:
      - "80"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://$USER:$PASSWORD@postgres:$DB_PORT/$DB_NAME
      - DEBUG=$DEBUG

  redis:
    hostname: redis
    restart: always
    image: redis:alpine
    command: redis-server --appendonly yes
    privileged: true
    ports:
      - "6379:6379"

  celery_worker:
    restart: always
    image: maciekj
    command: ./run_celery_worker.sh
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_URL=postgres://$USER:$PASSWORD@postgres:$DB_PORT/$DB_NAME
    links:
      - postgres
      - redis
    depends_on:
      - redis
    volumes_from:
      - web
