version: '3'
services:
  postgres:
    restart: always
    image: postgres:11.5
    volumes:
      - /docker/icloud:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=${PASSWORD:-postgres}
      - POSTGRES_USER=${USER:-postgres}
      - POSTGRES_DB={$DB_NAME:-postgres}
    ports:
      - 5432-5432

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - /docker/icloud/config/nginx:/etc/nginx/conf.d
      - /docker/icloud/static:/static
      - /docker/icloud/media:/media
      - /docker/icloud/nginx_logs:/var/log/nginx/
    depends_on:
      - web

  web:
    image: icloud
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - ./wait-for-postgres.sh
      - ./entrypoint.sh
    volumes:
      - /docker/icloud:/src
      - /docker/icloud/static:/static
      - /docker/icloud/media:/media
      - /docker/icloud/nginx_logs:/nginx_logs
    expose:
      - "80"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://$USER:$PASSWORD@postgres:$DB_PORT/$DB_NAME

  redis:
    hostname: redis
    restart: always
    image: redis:alpine
    command: redis-server --appendonly yes
    privileged: true
    ports:
      - "6379:6379"

  celery_worker:
    restart: always
    command: ./run_celery_worker.sh
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_URL=postgres://$USER:$PASSWORD@postgres:5432/$DB_NAME
    links:
      - postgres
      - redis
    depends_on:
      - redis
    volumes_from:
      - web
